### ISSUE TITLE
请问dell7566能否使用这个EFI

### ISSUE THREAD

**Issue by GeekZed** [worship76/dell7559_Hackintosh_Monterey#4]
以下是鲁大师配置
	
电脑型号	戴尔 Inspiron 7566 笔记本电脑  (扫描时间：2021年09月10日)
操作系统	Windows 10 专业版 64位 ( DirectX 12 )
	
处理器	英特尔 Core i5-6300HQ @ 2.30GHz 四核
主板	戴尔 0293F5 ( 100 Series/C230 Series 芯片组 Family - A14E )
内存	12 GB ( 海力士 DDR4 2400MHz / 金士顿 DDR4 2400MHz )
主硬盘	闪迪 X400 M.2 2280 128GB ( 128 GB / 固态硬盘 )
主显卡	Nvidia GeForce GTX 960M ( 4 GB / 戴尔 )
显示器	奇美 CMN15C4 ( 15.5 英寸  )
声卡	瑞昱  @ 英特尔 High Definition Audio 控制器 
网卡	瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller / 戴尔
	
网卡	瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller
制造商	戴尔
	
无线网卡	英特尔 Dual Band Wireless-AC 3165
	
声卡	瑞昱  @ 英特尔 High Definition Audio 控制器
	
键盘	HID 标准键盘
键盘	PS/2 标准键盘
键盘	HID 标准键盘
鼠标	HID-compliant 鼠标
鼠标	PS/2 兼容鼠标
鼠标	HID-compliant 鼠标
	
摄像头	瑞昱 Integrated Webcam
	
显卡	英特尔 HD Graphics 530
显存	128 MB
制造商	戴尔
驱动版本	27.20.100.8681
驱动日期	20200905
	
主显卡	Nvidia GeForce GTX 960M
显存	4 GB
制造商	戴尔
驱动版本	27.21.14.5771
驱动日期	20201229

**Comment by worship-dog** [comment]
主板型号不一样，应该是不能用的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月10日(周五) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [worship76/dell7559_Hackintosh_BigSur] 请问dell7566能否使用这个EFI (#4)




 
以下是鲁大师配置
 
电脑型号戴尔 Inspiron 7566 笔记本电脑  (扫描时间：2021年09月10日)
 操作系统Windows 10 专业版 64位 ( DirectX 12 )
 
处理器英特尔 Core i5-6300HQ @ 2.30GHz 四核
 主板戴尔 0293F5 ( 100 Series/C230 Series 芯片组 Family - A14E )
 内存12 GB ( 海力士 DDR4 2400MHz / 金士顿 DDR4 2400MHz )
 主硬盘闪迪 X400 M.2 2280 128GB ( 128 GB / 固态硬盘 )
 主显卡Nvidia GeForce GTX 960M ( 4 GB / 戴尔 )
 显示器奇美 CMN15C4 ( 15.5 英寸  )
 声卡瑞昱  @ 英特尔 High Definition Audio 控制器
 网卡瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller / 戴尔
 
网卡瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller
 制造商戴尔
 
无线网卡英特尔 Dual Band Wireless-AC 3165
 
声卡瑞昱  @ 英特尔 High Definition Audio 控制器
 
键盘HID 标准键盘
 键盘PS/2 标准键盘
 键盘HID 标准键盘
 鼠标HID-compliant 鼠标
 鼠标PS/2 兼容鼠标
 鼠标HID-compliant 鼠标
 
摄像头瑞昱 Integrated Webcam
 
显卡英特尔 HD Graphics 530
 显存128 MB
 制造商戴尔
 驱动版本27.20.100.8681
 驱动日期20200905
 
主显卡Nvidia GeForce GTX 960M
 显存4 GB
 制造商戴尔
 驱动版本27.21.14.5771
 驱动日期20201229
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GeekZed** [comment]
嘿大兄弟！我的机型试了你的efi目前基本一切正常！！！！非常感谢！！！只有几个小问题：
1.外放的声道貌似偏左（问题不大，能响哈哈）
2.蓝牙耳机连接不太稳定，声音会断断续续（很少用到，问题不大，可以插有线耳机代替）
3.没识别有线网
其他暂时没发现。太开心了，感谢！

**Comment by worship-dog** [comment]
声音的话参考这个[教程](https://www.bilibili.com/video/BV1dp4y1D7r8?spm_id_from=333.999.0.0)，换一个适合你机型的alcid可能会有所改善。如果有条件，连接5Ghz的wifi能提升蓝牙连接质量。有线网卡不能用我就不清楚什么问题了。你可以按照这个[教程](https://www.bilibili.com/video/BV1aV411e7Vo?spm_id_from=333.999.0.0)，重新定制一下usb，以免usb3.0不能正常使用

**Comment by GeekZed** [comment]
好的感谢！
